[package]
name = "8d-audio-maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hrtf = "0.8.0"
wav = "1.0.0"
